# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'WhiteBoardWebDemo' do

pod 'Toast', '~> 2.4'
pod 'SDWebImage', '~> 3.7.1'
pod 'SVProgressHUD', '~> 1.1.2'
pod 'CocoaLumberjack', '~> 2.2.0'
pod 'Reachability', '~> 3.1.1'
pod 'Masonry', '~> 1.1.0'

end

